/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * API version: 1.0.0
 * Contact: support@lagrello.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagrello-go

import (
	"encoding/json"
)

// CreateTenantRequest struct for CreateTenantRequest
type CreateTenantRequest struct {
	// The name of the tenant should preferably be the name of your organization/company. Does not need to be but your end users will see this name.
	TenantName string `json:"tenantName"`
	// Email to the person that will be tenant admin.
	AdminEmail string `json:"adminEmail"`
}

// NewCreateTenantRequest instantiates a new CreateTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTenantRequest(tenantName string, adminEmail string) *CreateTenantRequest {
	this := CreateTenantRequest{}
	this.TenantName = tenantName
	this.AdminEmail = adminEmail
	return &this
}

// NewCreateTenantRequestWithDefaults instantiates a new CreateTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTenantRequestWithDefaults() *CreateTenantRequest {
	this := CreateTenantRequest{}
	return &this
}

// GetTenantName returns the TenantName field value
func (o *CreateTenantRequest) GetTenantName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantName
}

// GetTenantNameOk returns a tuple with the TenantName field value
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetTenantNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TenantName, true
}

// SetTenantName sets field value
func (o *CreateTenantRequest) SetTenantName(v string) {
	o.TenantName = v
}

// GetAdminEmail returns the AdminEmail field value
func (o *CreateTenantRequest) GetAdminEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdminEmail
}

// GetAdminEmailOk returns a tuple with the AdminEmail field value
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetAdminEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AdminEmail, true
}

// SetAdminEmail sets field value
func (o *CreateTenantRequest) SetAdminEmail(v string) {
	o.AdminEmail = v
}

func (o CreateTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tenantName"] = o.TenantName
	}
	if true {
		toSerialize["adminEmail"] = o.AdminEmail
	}
	return json.Marshal(toSerialize)
}

type NullableCreateTenantRequest struct {
	value *CreateTenantRequest
	isSet bool
}

func (v NullableCreateTenantRequest) Get() *CreateTenantRequest {
	return v.value
}

func (v *NullableCreateTenantRequest) Set(val *CreateTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTenantRequest(val *CreateTenantRequest) *NullableCreateTenantRequest {
	return &NullableCreateTenantRequest{value: val, isSet: true}
}

func (v NullableCreateTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


