/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * API version: 1.0.0
 * Contact: support@lagrello.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagrello-go

import (
	"encoding/json"
)

// ActivateTenantRequest struct for ActivateTenantRequest
type ActivateTenantRequest struct {
	// The full name of your company.
	CompanyName string `json:"companyName"`
	// The first line of the address for your company.
	CompanyAddress string `json:"companyAddress"`
	// The city in which the address is located.
	CompanyCity string `json:"companyCity"`
	// The postal code for the address.
	CompanyPostalCode string `json:"companyPostalCode"`
	// The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).
	CompanyCountry string `json:"companyCountry"`
	// Your company's organization number.
	CompanyOrgNumber string `json:"companyOrgNumber"`
	// A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.
	CompanyVATNumber string `json:"companyVATNumber"`
}

// NewActivateTenantRequest instantiates a new ActivateTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateTenantRequest(companyName string, companyAddress string, companyCity string, companyPostalCode string, companyCountry string, companyOrgNumber string, companyVATNumber string) *ActivateTenantRequest {
	this := ActivateTenantRequest{}
	this.CompanyName = companyName
	this.CompanyAddress = companyAddress
	this.CompanyCity = companyCity
	this.CompanyPostalCode = companyPostalCode
	this.CompanyCountry = companyCountry
	this.CompanyOrgNumber = companyOrgNumber
	this.CompanyVATNumber = companyVATNumber
	return &this
}

// NewActivateTenantRequestWithDefaults instantiates a new ActivateTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateTenantRequestWithDefaults() *ActivateTenantRequest {
	this := ActivateTenantRequest{}
	return &this
}

// GetCompanyName returns the CompanyName field value
func (o *ActivateTenantRequest) GetCompanyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyName, true
}

// SetCompanyName sets field value
func (o *ActivateTenantRequest) SetCompanyName(v string) {
	o.CompanyName = v
}

// GetCompanyAddress returns the CompanyAddress field value
func (o *ActivateTenantRequest) GetCompanyAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyAddress
}

// GetCompanyAddressOk returns a tuple with the CompanyAddress field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyAddress, true
}

// SetCompanyAddress sets field value
func (o *ActivateTenantRequest) SetCompanyAddress(v string) {
	o.CompanyAddress = v
}

// GetCompanyCity returns the CompanyCity field value
func (o *ActivateTenantRequest) GetCompanyCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyCity
}

// GetCompanyCityOk returns a tuple with the CompanyCity field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyCityOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyCity, true
}

// SetCompanyCity sets field value
func (o *ActivateTenantRequest) SetCompanyCity(v string) {
	o.CompanyCity = v
}

// GetCompanyPostalCode returns the CompanyPostalCode field value
func (o *ActivateTenantRequest) GetCompanyPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyPostalCode
}

// GetCompanyPostalCodeOk returns a tuple with the CompanyPostalCode field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyPostalCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyPostalCode, true
}

// SetCompanyPostalCode sets field value
func (o *ActivateTenantRequest) SetCompanyPostalCode(v string) {
	o.CompanyPostalCode = v
}

// GetCompanyCountry returns the CompanyCountry field value
func (o *ActivateTenantRequest) GetCompanyCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyCountry
}

// GetCompanyCountryOk returns a tuple with the CompanyCountry field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyCountryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyCountry, true
}

// SetCompanyCountry sets field value
func (o *ActivateTenantRequest) SetCompanyCountry(v string) {
	o.CompanyCountry = v
}

// GetCompanyOrgNumber returns the CompanyOrgNumber field value
func (o *ActivateTenantRequest) GetCompanyOrgNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyOrgNumber
}

// GetCompanyOrgNumberOk returns a tuple with the CompanyOrgNumber field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyOrgNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyOrgNumber, true
}

// SetCompanyOrgNumber sets field value
func (o *ActivateTenantRequest) SetCompanyOrgNumber(v string) {
	o.CompanyOrgNumber = v
}

// GetCompanyVATNumber returns the CompanyVATNumber field value
func (o *ActivateTenantRequest) GetCompanyVATNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyVATNumber
}

// GetCompanyVATNumberOk returns a tuple with the CompanyVATNumber field value
// and a boolean to check if the value has been set.
func (o *ActivateTenantRequest) GetCompanyVATNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyVATNumber, true
}

// SetCompanyVATNumber sets field value
func (o *ActivateTenantRequest) SetCompanyVATNumber(v string) {
	o.CompanyVATNumber = v
}

func (o ActivateTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["companyName"] = o.CompanyName
	}
	if true {
		toSerialize["companyAddress"] = o.CompanyAddress
	}
	if true {
		toSerialize["companyCity"] = o.CompanyCity
	}
	if true {
		toSerialize["companyPostalCode"] = o.CompanyPostalCode
	}
	if true {
		toSerialize["companyCountry"] = o.CompanyCountry
	}
	if true {
		toSerialize["companyOrgNumber"] = o.CompanyOrgNumber
	}
	if true {
		toSerialize["companyVATNumber"] = o.CompanyVATNumber
	}
	return json.Marshal(toSerialize)
}

type NullableActivateTenantRequest struct {
	value *ActivateTenantRequest
	isSet bool
}

func (v NullableActivateTenantRequest) Get() *ActivateTenantRequest {
	return v.value
}

func (v *NullableActivateTenantRequest) Set(val *ActivateTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateTenantRequest(val *ActivateTenantRequest) *NullableActivateTenantRequest {
	return &NullableActivateTenantRequest{value: val, isSet: true}
}

func (v NullableActivateTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


