/*
 * Lagrello API
 *
 * API specification for Lagrello, a simple to use authentication service
 *
 * API version: 1.0.0
 * Contact: support@lagrello.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagrello-go

import (
	"encoding/json"
)

// Tenant Tenant is what you can call your account with lagrello. In your tenant you will store all the information about your account and all your users accounts.
type Tenant struct {
	TenantId string `json:"tenantId"`
	TenantName string `json:"tenantName"`
	CallbackUrl string `json:"callbackUrl"`
	CompanyInfo TenantCompanyInfo `json:"companyInfo"`
	Activated bool `json:"activated"`
}

// NewTenant instantiates a new Tenant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenant(tenantId string, tenantName string, callbackUrl string, companyInfo TenantCompanyInfo, activated bool) *Tenant {
	this := Tenant{}
	this.TenantId = tenantId
	this.TenantName = tenantName
	this.CallbackUrl = callbackUrl
	this.CompanyInfo = companyInfo
	this.Activated = activated
	return &this
}

// NewTenantWithDefaults instantiates a new Tenant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantWithDefaults() *Tenant {
	this := Tenant{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *Tenant) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *Tenant) GetTenantIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *Tenant) SetTenantId(v string) {
	o.TenantId = v
}

// GetTenantName returns the TenantName field value
func (o *Tenant) GetTenantName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantName
}

// GetTenantNameOk returns a tuple with the TenantName field value
// and a boolean to check if the value has been set.
func (o *Tenant) GetTenantNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TenantName, true
}

// SetTenantName sets field value
func (o *Tenant) SetTenantName(v string) {
	o.TenantName = v
}

// GetCallbackUrl returns the CallbackUrl field value
func (o *Tenant) GetCallbackUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value
// and a boolean to check if the value has been set.
func (o *Tenant) GetCallbackUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CallbackUrl, true
}

// SetCallbackUrl sets field value
func (o *Tenant) SetCallbackUrl(v string) {
	o.CallbackUrl = v
}

// GetCompanyInfo returns the CompanyInfo field value
func (o *Tenant) GetCompanyInfo() TenantCompanyInfo {
	if o == nil {
		var ret TenantCompanyInfo
		return ret
	}

	return o.CompanyInfo
}

// GetCompanyInfoOk returns a tuple with the CompanyInfo field value
// and a boolean to check if the value has been set.
func (o *Tenant) GetCompanyInfoOk() (*TenantCompanyInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CompanyInfo, true
}

// SetCompanyInfo sets field value
func (o *Tenant) SetCompanyInfo(v TenantCompanyInfo) {
	o.CompanyInfo = v
}

// GetActivated returns the Activated field value
func (o *Tenant) GetActivated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Activated
}

// GetActivatedOk returns a tuple with the Activated field value
// and a boolean to check if the value has been set.
func (o *Tenant) GetActivatedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Activated, true
}

// SetActivated sets field value
func (o *Tenant) SetActivated(v bool) {
	o.Activated = v
}

func (o Tenant) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tenantId"] = o.TenantId
	}
	if true {
		toSerialize["tenantName"] = o.TenantName
	}
	if true {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	if true {
		toSerialize["companyInfo"] = o.CompanyInfo
	}
	if true {
		toSerialize["activated"] = o.Activated
	}
	return json.Marshal(toSerialize)
}

type NullableTenant struct {
	value *Tenant
	isSet bool
}

func (v NullableTenant) Get() *Tenant {
	return v.value
}

func (v *NullableTenant) Set(val *Tenant) {
	v.value = val
	v.isSet = true
}

func (v NullableTenant) IsSet() bool {
	return v.isSet
}

func (v *NullableTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenant(val *Tenant) *NullableTenant {
	return &NullableTenant{value: val, isSet: true}
}

func (v NullableTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


